---
title: "Validation"
author: "Christian Hunter"
date: "8/5/2020"
output: html_document
params:
  graph: Transit
---
```{r wfrc_tables, include=FALSE}
library(tidyverse)
#BiocManager::install("rhdf5")
library(rhdf5)
#devtools::install_github("cloudyr/rmote") # To easily see all plots
library(rmote)
#start_rmote() # run servr::daemon_stop(1) to stop

## Read in output files
wfrc_trips <- read_csv("validation/WFRC_trips.csv")
wfrc_school <- read_csv("validation/WFRC_school.csv")
as_trips <- read_csv("output/final_trips.csv")
as_tours <- read_csv("output/final_tours.csv", col_types = list(
  composition = col_character(), parent_tour_id = col_integer()))

## Modes List
auto <- c('DRIVEALONEFREE', "DRIVEALONETOLL", "SHARED2FREE", "SHARED2TOLL", 
          "SHARED3FREE", "SHARED3TOLL")
nonmotor <- c("Nonmotorized")
nonmotor_as <- c("BIKE", "WALK")
transit <- c("WALK_LOC", "DRIVE_LOC", "WALK_MAX", 'DRIVE_MAX', 'WALK_BRT', 'DRIVE_BRT',
             'WALK_EXP', 'DRIVE_EXP', 'WALK_TRAX', 'DRIVE_TRAX', 'WALK_COM', 'DRIVE_COM')
transit_as <- c("WALK_LOC", "DRIVE_LOC", "WALK_MAX", 'DRIVE_MAX', 'WALK_HVY', 'DRIVE_HVY',
             'WALK_EXP', 'DRIVE_EXP', 'WALK_LRF', 'DRIVE_LRF', 'WALK_COM', 'DRIVE_COM')
totals <- c('AUTO_TOTAL', 'TRANSIT_TOTAL')
combined_modes <- auto %>% 
  append(nonmotor) %>% 
  append(transit) %>% 
  append(totals)

## Organize WFRC summary to align with AS format
index_row <- c(6,7,9,10,13,14,2,18,19,21,22,24,25,27,28,30,31,33,34,1,16)
index_col <- c(2,5,8,11)
trip_types <- c("HWB_wf", "HBC_wf", "HBO_wf", "NHB_wf")
comp_table <- as.data.frame(combined_modes) 
comp_table[, trip_types] <- NA
for (type in 1:length(trip_types)){
  for (i in 1:length(index_row)){
    if (i == 1){
      vals <- wfrc_trips[index_row[i], index_col[type]]
    } else{
      vals <- vals %>% 
        append(wfrc_trips[index_row[i], index_col[type]])
    }
  }
  comp_table[[type + 1]] <- vals
}
```

```{r county_matrix, include=FALSE}
## Read in crosswalk from PopulationSim and list of external TAZs, remove these TAZs
xTAZs <- read_csv("validation/external_tazs.csv")
ps_xw <- read_csv("validation/geo_cross_walk.csv") %>% 
  filter(!TAZ %in% xTAZs$xTAZ) %>% 
  mutate(
    TAZ2 = case_when(
      TAZ < 136 ~ TAZ,
      TAZ > 140 & TAZ < 421 ~ (TAZ - 5),
      TAZ > 422 & TAZ < 1782 ~ (TAZ -7),
      T ~ (TAZ - 14)
    )
  ) %>% 
  subset(select = -c(TAZ, REGION, TRACT, geometry)) %>% 
  rename(TAZ = TAZ2)

## Find county for each trip origin and destination
as_trips <- as_trips %>% 
  mutate(
    ocounty = case_when(
      origin < 136 ~ "Box_Elder",
      origin > 135 & origin < 417 ~ "Weber",
      origin > 416 & origin < 648 ~ "Davis",
      origin > 647 & origin < 1775 ~ "Salt_Lake",
      origin > 1774 & origin < 2860 ~ "Utah",
      T ~ "NA"
    ),
    dcounty = case_when(
      destination < 136 ~ "Box_Elder",
      destination > 135 & destination < 417 ~ "Weber",
      destination > 416 & destination < 648 ~ "Davis",
      destination > 647 & destination < 1775 ~ "Salt_Lake",
      destination > 1774 & destination < 2860 ~ "Utah",
      T ~ "NA")
  )
```

```{r}
## Create OD matrix
od <- as_trips %>% 
  group_by(ocounty, dcounty) %>% 
  tally() %>% 
  spread(dcounty, n)
od
```


```{r distance_as, include=FALSE}
## Create trip length frequency distribution
skims = H5Fopen("data/skims_wfrc.omx")
dist = skims$"/data/DIST" %>% 
  as.data.frame()
distance <- rep(1, nrow(as_trips))
o_col <- as_trips$origin
d_col <- as_trips$destination

## Be patient, takes a couple minutes (FIXME - parallelize)
for (i in 1:nrow(as_trips)){
  o <- o_col[i]
  d <- d_col[i]
  distance[i] <- dist[o,d]
}
```

```{r distance_wfrc, include=FALSE}
## Open WFRC production-attraction OMX
pa_omx = H5Fopen("validation/AllTrips_pkok.mtx.omx")
omx_index <- h5ls(pa_omx) %>% 
  select(name)
## Open WFRC distance matrix (with 2881-TAZ numbering scheme)
dist_mtx <- H5Fopen("scripts/skm_auto_Ok.mtx.omx")
dTAZ <- rep(1:2881, times = 2881, each = 1)
oTAZ <- rep(1:2881, times = 1, each =2881) 
dist_v <- as.vector(as.numeric(dist_mtx$"/data/xydist")) %>% as.data.frame() 
## Add trip counts for each mode (ugly but but couldn't get a for loop to work yet)
DRIVEALONEFREE <- as.vector(t(pa_omx$"/data/DA")) %>% as.data.frame()
DRIVEALONEFREE <- cbind(DRIVEALONEFREE, dist_v)
DRIVEALONEFREE$mode <- "DRIVEALONEFREE"
SHARED2FREE <- as.vector(t(pa_omx$"/data/SR2")) %>% as.data.frame()
SHARED2FREE <- cbind(SHARED2FREE, dist_v)
SHARED2FREE$mode <- "SHARED2FREE"
SHARED3FREE <- as.vector(t(pa_omx$"/data/SR3p")) %>% as.data.frame()
SHARED3FREE <- cbind(SHARED3FREE, dist_v)
SHARED3FREE$mode <- "SHARED3FREE"
Auto <- as.vector(t(pa_omx$"/data/auto")) %>% as.data.frame()
Auto <- cbind(Auto, dist_v)
Auto$mode <- "Auto"
DRIVE_COM <- as.vector(t(pa_omx$"/data/dCRT")) %>% as.data.frame()
DRIVE_COM <- cbind(DRIVE_COM, dist_v)
DRIVE_COM$mode <- "DRIVE_COM"
DRIVE_EXP <- as.vector(t(pa_omx$"/data/dEXP")) %>% as.data.frame()
DRIVE_EXP <- cbind(DRIVE_EXP, dist_v)
DRIVE_EXP$mode <- "DRIVE_EXP"
DRIVE_LOC <- as.vector(t(pa_omx$"/data/dLCL")) %>% as.data.frame()
DRIVE_LOC <- cbind(DRIVE_LOC, dist_v)
DRIVE_LOC$mode <- "DRIVE_LOC"
DRIVE_LRF <- as.vector(t(pa_omx$"/data/dLRT")) %>% as.data.frame()
DRIVE_LRF <- cbind(DRIVE_LRF, dist_v)
DRIVE_LRF$mode <- "DRIVE_LRF"
DRIVE_HVY <- as.vector(t(pa_omx$"/data/dmode9")) %>% as.data.frame()
DRIVE_HVY <- cbind(DRIVE_HVY, dist_v)
DRIVE_HVY$mode <- "DRIVE_HVY"
Motor <- as.vector(t(pa_omx$"/data/motor")) %>% as.data.frame()
Motor <- cbind(Motor, dist_v)
Motor$mode <- "Motor"
Nonmotorized <- as.vector(t(pa_omx$"/data/nonmotor")) %>% as.data.frame()
Nonmotorized <- cbind(Nonmotorized, dist_v)
Nonmotorized$mode <- "Nonmotorized"
Transit <- as.vector(t(pa_omx$"/data/transit")) %>% as.data.frame()
Transit <- cbind(Transit, dist_v)
Transit$mode <- "Transit"
WALK_COM <- as.vector(t(pa_omx$"/data/wCRT")) %>% as.data.frame()
WALK_COM <- cbind(WALK_COM, dist_v)
WALK_COM$mode <- "WALK_COM"
WALK_EXP <- as.vector(t(pa_omx$"/data/wEXP")) %>% as.data.frame()
WALK_EXP <- cbind(WALK_EXP, dist_v)
WALK_EXP$mode <- "WALK_EXP"
WALK_LOC <- as.vector(t(pa_omx$"/data/wLCL")) %>% as.data.frame()
WALK_LOC <- cbind(WALK_LOC, dist_v)
WALK_LOC$mode <- "WALK_LOC"
WALK_LRF <- as.vector(t(pa_omx$"/data/wLRT")) %>% as.data.frame()
WALK_LRF <- cbind(WALK_LRF, dist_v)
WALK_LRF$mode <- "WALK_LRF"
WALK_HVY <- as.vector(t(pa_omx$"/data/wmode9")) %>% as.data.frame()
WALK_HVY <- cbind(WALK_HVY, dist_v)
WALK_HVY$mode <- "WALK_HVY"
## Combine into two dataframes, one with mode breakdowns and one with group summaries
wfrc_all <- rbind(DRIVEALONEFREE, SHARED2FREE, SHARED3FREE, DRIVE_COM, DRIVE_EXP, 
                   DRIVE_HVY, DRIVE_LOC, DRIVE_LRF, WALK_COM, WALK_EXP,  
                   WALK_HVY, WALK_LOC, WALK_LRF)
colnames(wfrc_all) <- c("count", "trip_length", "mode")
wfrc_all <- wfrc_all %>%  mutate(
    mode_group = case_when(
      mode %in% auto ~ "Auto",
      mode %in% nonmotor ~"Nonmotorized",
      mode %in% transit_as ~ "Transit"
    )
  )

wfrc_summary <- rbind(Transit, Nonmotorized, Auto)
colnames(wfrc_summary) <- c("count", "trip_length", "mode")
## Cleanup
rm(DRIVEALONEFREE, SHARED2FREE, SHARED3FREE, DRIVE_COM, DRIVE_EXP, 
                   DRIVE_HVY, DRIVE_LOC, DRIVE_LRF, WALK_COM, WALK_EXP,  
                   WALK_HVY, WALK_LOC, WALK_LRF, Transit, Nonmotorized, Auto)
```

```{r plots_galore, echo=FALSE}
## Histogram
as_trips <- as_trips%>% mutate(trip_length = distance)
ggplot(as_trips) + geom_histogram(aes(x = trip_length), binwidth = .5) + xlim(0,20) + 
  theme_bw(base_size = 18) + labs(y = "Frequency", x = "Trip Length")
## Line graph
ggplot(as_trips) + geom_freqpoly(aes(x = trip_length), binwidth = .25) + xlim(0,20) + 
  theme_bw(base_size = 18) + labs(y = "Frequency", x = "Trip Length")
## Line graph, segmented by mode
ggplot(as_trips) + geom_density(aes(x = trip_length, color = trip_mode)) + xlim(0,20) + 
  theme_bw(base_size = 18) + labs(y = "Frequency", x = "Trip Length", color = "Mode")
## Automobile modes
tlfd_a <- as_trips %>% 
  filter(trip_mode %in% auto) %>% 
  select(c(trip_mode, trip_length))
ggplot(tlfd_a) + geom_density(aes(x = trip_length, color = trip_mode)) + xlim(0,20) + 
  theme_bw(base_size = 18) + labs(y = "Frequency", x = "Trip Length", color = "Mode")
## Nonmotorized modes
tlfd_n <- as_trips %>% 
  filter(trip_mode %in% nonmotor_as) %>% 
  select(c(trip_mode, trip_length))
ggplot(tlfd_n) + geom_density(aes(x = trip_length, color = trip_mode)) + xlim(0,20) + 
  theme_bw(base_size = 18) + labs(y = "Frequency", x = "Trip Length", color = "Mode")
## Transit modes
tlfd_t <- as_trips %>% 
  filter(trip_mode %in% transit_as) %>% 
  select(c(trip_mode, trip_length))
ggplot(tlfd_t) + geom_density(aes(x = trip_length, color = trip_mode)) + xlim(0,20) + 
theme_bw(base_size = 18) + labs(y = "Frequency", x = "Trip Length", color = "Mode")
## By mode group
as_trips <- as_trips %>% 
  mutate(
    mode_group = case_when(
      trip_mode %in% auto ~ "Auto",
      trip_mode %in% nonmotor_as ~"Nonmotorized",
      trip_mode %in% transit_as ~ "Transit"
    )
  )
ggplot(as_trips) + geom_density(aes(x = trip_length, color = mode_group)) + xlim(0,20) + 
theme_bw(base_size = 18) + labs(y = "Frequency", x = "Trip Length", color = "Mode")
## There is a large difference between nonmotorized and the other two groups, so separate them
a_vs_t <- as_trips %>% 
  select(c(trip_length, mode_group)) %>% 
  filter(!mode_group == "Nonmotorized")
ggplot(a_vs_t) + geom_density(aes(x = trip_length, color = mode_group)) + xlim(0,20) + 
theme_bw(base_size = 18) + labs(y = "Frequency", x = "Trip Length", color = "Mode")
as_transit <- a_vs_t %>% 
  filter(mode_group == "Transit")
```

```{r comparison, include=FALSE}
## TLFD comparison graphics
## By mode group
ggplot(wfrc_summary) + geom_density(aes(x = trip_length, color = mode, weight = count)) +
  xlim(0,20) + theme_bw(base_size = 18) + 
  labs(y = "Frequency", x = "Trip Length", color = "Mode")

wfrc_transit <- wfrc_summary %>% 
  filter(mode == "Transit")
ggplot(wfrc_transit) + geom_density(aes(x = trip_length, color = "WFRC", weight = count)) +
  geom_density(data = as_transit, aes(x = trip_length, color = "ActivtySim")) + xlim(0,20) + theme_bw(base_size = 18) + 
  labs(y = "Frequency", x = "Trip Length", color = "Model")

m_index <- c("DRIVEALONEFREE", "SHARED2FREE", "SHARED3FREE", "DRIVE_COM", "DRIVE_EXP",
             "DRIVE_HVY", "DRIVE_LOC", "DRIVE_LRF", "WALK_COM", "WALK_EXP", "WALK_HVY",
             "WALK_LOC", "WALK_LRF")
s_index <- c("Auto", "Transit", "Nonmotorized")
```

```{r plotter}
plotter <- function(graph, limit){
  if (graph %in% m_index){
    as_temp <- as_trips %>% 
      filter(trip_mode %in% graph) %>% 
      select(trip_length, trip_mode)
    wf_temp <- wfrc_all %>% 
      filter(mode %in% graph)
    pic <- ggplot(wf_temp) + 
      geom_density(aes(x = trip_length, color = "WFRC", weight = count)) +
      geom_density(data = as_temp, aes(x = trip_length, color = "ActivtySim")) + 
      xlim(0,limit) + theme_bw(base_size = 18) + 
      labs(y = "Frequency", x = "Trip Length", color = "Model", title = graph)
    pic
  } else if (graph %in% s_index){
    as_temp <- as_trips %>% 
      filter(mode_group %in% graph) %>% 
      select(trip_length, mode_group)
    wf_temp <- wfrc_summary %>% 
      filter(mode %in% graph)
    pic <- ggplot(wf_temp) + 
      geom_density(aes(x = trip_length, color = "WFRC", weight = count)) +
      geom_density(data = as_temp, aes(x = trip_length, color = "ActivtySim")) + 
      xlim(0,limit) + theme_bw(base_size = 18) + 
      labs(y = "Frequency", x = "Trip Length", color = "Model", title = graph)
    pic
  } else {
    print("Try again")
  }
}
```

```{r as_stats, eval=FALSE, include=FALSE}
## Show all AS trip combinations
combos <- group_by(as_trips, primary_purpose, purpose, trip_count) %>% tally() %>% print(n=100)

## Get HBW stats
as_hbw <- as_trips %>% 
  mutate(labels = case_when(
    trip_num == 1 & purpose == "work" ~ "HBW",
    trip_num == 1 & purpose == "Home" & primary_purpose == "work" ~ "HBW"
  )) %>% 
  group_by(labels, trip_mode) %>%
  tally() %>% 
  filter(labels %in% "HBW")

## Get HBO stats
as_hbo <- as_trips %>% 
  mutate(labels = case_when(
    trip_num == 1 & purpose != "work" & primary_purpose != "atwork" & 
    purpose != "school" ~ "HBO"
  )) %>% 
  group_by(labels, trip_mode) %>%
  tally() %>% 
  filter(labels %in% "HBO")

## Get NHB stats
as_nhb <- as_trips %>% 
   mutate(labels = case_when(
    trip_num == 1 & primary_purpose == "work" & purpose != "work" & purpose != "Home" ~ "NHB" 
  )) %>% 
  group_by(labels, trip_mode) %>%
  tally() %>% 
  filter(labels %in% "NHB")

## Get HBShop stats
as_hbc <- as_trips %>%
 mutate(labels = case_when(
    trip_num == 1 & primary_purpose == "work" & purpose != "work" ~ "HBC"
  )) %>% 
  group_by(labels, trip_mode) %>%
  tally() %>% 
  filter(labels %in% "HBC") 

## Combine tables
comp_table <- comp_table %>% 
  add_column(HBW_as = 0, .after = 2) %>% 
  add_column(HBO_as = 0, .after = 5)
for (i in 1: length(as_hbw$trip_mode)){
  row = match(as_hbw$trip_mode[i], combined_modes)
  comp_table$HBW_as[row] = as_hbw$n[i]
}
for (i in 1: length(as_hbo$trip_mode)){
  row = match(as_hbo$trip_mode[i], combined_modes)
  comp_table$HBO_as[row] = as_hbo$n[i]
}



```
